// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxLqPdqKskABrtHYO2EQDDyc2dzXtXykE',
    appId: '1:605630445144:android:3ca56995d18a244e2d7c2d',
    messagingSenderId: '605630445144',
    projectId: 'pishingdetectapp',
    storageBucket: 'pishingdetectapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpKFu26IyZ9DHXgkF-WiQjzIl_zUxm5DU',
    appId: '1:605630445144:ios:45394d3c25e059132d7c2d',
    messagingSenderId: '605630445144',
    projectId: 'pishingdetectapp',
    storageBucket: 'pishingdetectapp.appspot.com',
    androidClientId: '605630445144-2sg9euclm8j3de81hlodh8m3qtta7klv.apps.googleusercontent.com',
    iosClientId: '605630445144-jkcanvkbithgrcviqedm5m4dps18rg08.apps.googleusercontent.com',
    iosBundleId: 'com.example.phishingDetectionApp',
  );
}
